routes:
  /: home
  /articles/:
    controller: channel
    data:       tag.articles
    filter:     tag:articles
    template:   tag
  /current-linguistics/:
    controller: channel
    data:       tag.current-linguistics
    filter:     tag:current-linguistics
    template:   tag
  /encyclopedia/:
    controller: channel
    data:       tag.encyclopedia
    filter:     tag:encyclopedia
    order:      title asc
    template:   tag
  /languages/:
    controller: channel
    data:       tag.languages
    filter:     tag:languages
    order:      title asc
    template:   tag
  /reviews/:
    controller: channel
    data:       tag.reviews
    filter:     tag:reviews
    template:   tag

collections:
  /posts/:
    permalink: /posts/{slug}/
    template:  index

taxonomies:
  author: /authors/{slug}/
  tag:    /tags/{slug}/